// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKlSamqzlzrSYUJVnlhyK4O6tdJ0YREfU',
    appId: '1:116159923534:web:12696f1f6eb877e2ff0a1f',
    messagingSenderId: '116159923534',
    projectId: 'cp-connects',
    authDomain: 'cp-connects.firebaseapp.com',
    storageBucket: 'cp-connects.appspot.com',
    measurementId: 'G-K0K3NCRFY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdqjpXo1jHvgZTS-zdxPyjcQ3mZl0qME',
    appId: '1:116159923534:android:1975b032d480c701ff0a1f',
    messagingSenderId: '116159923534',
    projectId: 'cp-connects',
    storageBucket: 'cp-connects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC-E-qAZj8wrtHhGsGBeLvfKHvorAbDLc',
    appId: '1:116159923534:ios:35f083437d894579ff0a1f',
    messagingSenderId: '116159923534',
    projectId: 'cp-connects',
    storageBucket: 'cp-connects.appspot.com',
    iosBundleId: 'com.example.cpConnects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC-E-qAZj8wrtHhGsGBeLvfKHvorAbDLc',
    appId: '1:116159923534:ios:e3dcf2cb03b49aeaff0a1f',
    messagingSenderId: '116159923534',
    projectId: 'cp-connects',
    storageBucket: 'cp-connects.appspot.com',
    iosBundleId: 'com.example.cpConnects.RunnerTests',
  );
}
